name: noteu_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.0.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  backdrop: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
  
  fonts:
    - family: Poppins-Regular # Nombre de la fuente
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
